repo_paths:
  - C:\Users\John\Documents\GitHub\AIprojectGroup9

file_types:
  - ".py"
  - ".java"
  - ".html"
  - ".css"
  - ".js"
  - ".ipynb"

models:
  - qwen2.5-coder:14b
  - llama3:latest
  - codellama:7b

prompt_method: chain
training_data_path: "py_training.jsonl"
