repo_paths:
  #- D:\PyCharm\Workspace\Projects\AI Project\Repos\Well Documented
  - D:\PyCharm\Workspace\Projects\AI Project\Repos\Bad Documentation\django_project-master

file_types: ['.py', '.java', '.js', '.html', '.ipynb', '.css']

models:
  - qwen2.5-coder:14b
  - llama3:latest
  - codellama:7b

prompt_method: chain
